[build]
  # Build command for Next.js application
  command = "cd gospel-admin && npm ci && npm run build"
  
  # Let Netlify auto-detect the publish directory for Next.js
  publish = ""
  
  # Environment variables for build process
  [build.environment]
    NODE_VERSION = "20"
    NEXT_PUBLIC_APP_NAME = "Gospel Presentation"
    NEXT_PUBLIC_APP_DESCRIPTION = "Presenting the Gospel in its Context"

# Modern Netlify automatically detects and handles Next.js projects
# API routes will work as Edge Functions automatically

[context.production]
  command = "cd gospel-admin && npm ci && npm run build"

[context.deploy-preview]
  command = "cd gospel-admin && npm ci && npm run build"

[context.branch-deploy]
  command = "cd gospel-admin && npm ci && npm run build"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/data.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"