[build]
  # Build from the Next.js subdirectory
  base = "gospel-admin"
  command = "npm run build"
  publish = ".next"
  
  # Environment variables for build process
  [build.environment]
    NODE_VERSION = "20"
    NEXT_PUBLIC_APP_NAME = "Gospel Presentation"
    NEXT_PUBLIC_APP_DESCRIPTION = "Presenting the Gospel in its Context"

# Essential Next.js Plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"