/**
 * Canonical USFM book codes for Calvin commentaries (matches {@link bookNameToUsfm} / API.Bible).
 * CCEL `osisRef` often uses longer or alternate abbreviations (e.g. `Exod`, `Matt`, `Acts`).
 */

/** Protestant canon order (66 books). */
export const CANONICAL_BIBLE_USFM_ORDER: readonly string[] = [
  'GEN',
  'EXO',
  'LEV',
  'NUM',
  'DEU',
  'JOS',
  'JDG',
  'RUT',
  '1SA',
  '2SA',
  '1KI',
  '2KI',
  '1CH',
  '2CH',
  'EZR',
  'NEH',
  'EST',
  'JOB',
  'PSA',
  'PRO',
  'ECC',
  'SNG',
  'ISA',
  'JER',
  'LAM',
  'EZK',
  'DAN',
  'HOS',
  'JOL',
  'AMO',
  'OBA',
  'JON',
  'MIC',
  'NAM',
  'HAB',
  'ZEP',
  'HAG',
  'ZEC',
  'MAL',
  'MAT',
  'MRK',
  'LUK',
  'JHN',
  'ACT',
  'ROM',
  '1CO',
  '2CO',
  'GAL',
  'EPH',
  'PHP',
  'COL',
  '1TH',
  '2TH',
  '1TI',
  '2TI',
  'TIT',
  'PHM',
  'HEB',
  'JAS',
  '1PE',
  '2PE',
  '1JN',
  '2JN',
  '3JN',
  'JUD',
  'REV',
] as const

const CANON_ORDER_INDEX = new Map<string, number>(
  CANONICAL_BIBLE_USFM_ORDER.map((code, i) => [code, i])
)

/** OSIS / CCEL abbreviations → canonical USFM (keys uppercase, no dots). */
const OSIS_BOOK_TO_CANONICAL_USFM: Record<string, string> = {
  GEN: 'GEN',
  EXO: 'EXO',
  EXOD: 'EXO',
  LEV: 'LEV',
  NUM: 'NUM',
  DEU: 'DEU',
  DEUT: 'DEU',
  JOS: 'JOS',
  JOSH: 'JOS',
  JDG: 'JDG',
  JUDG: 'JDG',
  RUT: 'RUT',
  '1SA': '1SA',
  '1SAM': '1SA',
  '2SA': '2SA',
  '2SAM': '2SA',
  '1KI': '1KI',
  '1KGS': '1KI',
  '2KI': '2KI',
  '2KGS': '2KI',
  '1CH': '1CH',
  '1CHR': '1CH',
  '2CH': '2CH',
  '2CHR': '2CH',
  EZR: 'EZR',
  NEH: 'NEH',
  EST: 'EST',
  ESTH: 'EST',
  JOB: 'JOB',
  PSA: 'PSA',
  PS: 'PSA',
  PRO: 'PRO',
  ECC: 'ECC',
  SNG: 'SNG',
  ISA: 'ISA',
  JER: 'JER',
  LAM: 'LAM',
  EZK: 'EZK',
  EZEK: 'EZK',
  DAN: 'DAN',
  HOS: 'HOS',
  JOL: 'JOL',
  AMO: 'AMO',
  OBA: 'OBA',
  JON: 'JON',
  MIC: 'MIC',
  NAM: 'NAM',
  NAH: 'NAM',
  HAB: 'HAB',
  ZEP: 'ZEP',
  HAG: 'HAG',
  ZEC: 'ZEC',
  MAL: 'MAL',
  MAT: 'MAT',
  MATT: 'MAT',
  MRK: 'MRK',
  MARK: 'MRK',
  LUK: 'LUK',
  LUKE: 'LUK',
  JHN: 'JHN',
  JOHN: 'JHN',
  ACT: 'ACT',
  ACTS: 'ACT',
  ROM: 'ROM',
  '1CO': '1CO',
  '1COR': '1CO',
  '2CO': '2CO',
  '2COR': '2CO',
  GAL: 'GAL',
  EPH: 'EPH',
  PHP: 'PHP',
  COL: 'COL',
  '1TH': '1TH',
  '1THESS': '1TH',
  '2TH': '2TH',
  '2THESS': '2TH',
  '1TI': '1TI',
  '1TIM': '1TI',
  '2TI': '2TI',
  '2TIM': '2TI',
  TIT: 'TIT',
  PHM: 'PHM',
  HEB: 'HEB',
  JAS: 'JAS',
  '1PE': '1PE',
  '1PET': '1PE',
  '2PE': '2PE',
  '2PET': '2PE',
  '1JN': '1JN',
  '1JOH': '1JN',
  '2JN': '2JN',
  '2JOH': '2JN',
  '3JN': '3JN',
  '3JOH': '3JN',
  JUD: 'JUD',
  REV: 'REV',
  REVELATION: 'REV',
}

/**
 * Map a raw OSIS/CCEL book fragment to canonical USFM, or null if unknown.
 */
export function normalizeCalvinBookUsfm(raw: string | null | undefined): string | null {
  if (!raw?.trim()) return null
  const key = raw.trim().toUpperCase().replace(/\./g, '')
  if (OSIS_BOOK_TO_CANONICAL_USFM[key]) return OSIS_BOOK_TO_CANONICAL_USFM[key]
  if (CANON_ORDER_INDEX.has(key)) return key
  return null
}

export function canonOrderIndexForUsfm(usfm: string): number {
  const n = CANON_ORDER_INDEX.get(usfm.toUpperCase())
  return n ?? 9999
}
