import type { ProfileContentHooksSlice } from '@/lib/profileContentHooksTypes'

export function makeProfileContentHooksSlice(
  overrides: Partial<ProfileContentHooksSlice> = {}
): ProfileContentHooksSlice {
  const closeBibleReader = jest.fn()
  const handleScriptureClick = jest.fn()

  return {
    ready: true,
    profileInfo: {
      title: 'Default',
      slug: 'default',
      favoriteScriptures: ['John 3:16'],
    },
    sections: [{ id: 's1', title: 'Section', subsections: [] } as never],
    profileSlug: 'default',
    profileTitle: 'Default',
    footerAttributionEnabledCodes: ['esv'],
    fromEditor: false,
    canEdit: false,
    isMenuOpen: false,
    toggleMenu: jest.fn(),
    closeMenu: jest.fn(),
    openMenu: jest.fn(),
    deferCloseMenuForFilePickerRef: { current: false },
    dailyVerseChallengeVersion: 0,
    isSharingResource: false,
    handleShareResource: jest.fn(),
    presentationMarkedReadComplete: false,
    handleMarkPresentationUnread: jest.fn(),
    versePinsList: [],
    handleRemoveVersePin: jest.fn(),
    handleClearAllVersePins: jest.fn(),
    highlightRevision: 0,
    bumpHighlights: jest.fn(),
    highlightsByScopeId: {},
    activeHighlightId: null,
    focusHighlightById: jest.fn(),
    requestRemoveHighlightFromBody: jest.fn(),
    resourceTabs: [],
    mainContentRef: { current: null },
    resourceSearchOpen: false,
    handleToggleResourceSearch: jest.fn(),
    handleSelectResourceTab: jest.fn(),
    handleCloseResourceTab: jest.fn(),
    scriptureModal: {
      activeScripture: { reference: 'Romans 8:1', isOpen: true },
      effectiveModalOpenAnchors: null,
      scriptureModalPresentationLocation: undefined,
      scriptureModalHighlightPicker: false,
      mcheyneDayListenReferences: undefined,
      syncMcheynePlaylistChapter: jest.fn(),
      closeModal: jest.fn(),
      openScriptureFromTabEntry: jest.fn(),
      navigateScriptureInReader: jest.fn(),
      clearMcheynePlanCardPinSession: jest.fn(),
      hasPrevious: true,
      hasNext: true,
      navigateToPrevious: jest.fn(),
      navigateToNext: jest.fn(),
      modalPinDraftColor: 'yellow',
      modalPinSyncedKey: null,
      modalPinDropdownColors: [],
      setModalPinUserOverride: jest.fn(),
      handleScriptureClick,
    } as ProfileContentHooksSlice['scriptureModal'],
    studyModals: {
      isSpurgeonLibraryOpen: false,
      isMorneveLibraryOpen: false,
      isMcheynePlanModalOpen: false,
      bibleReaderOpen: true,
      studyModalTitle: 'Study',
      studyLibraryFocus: 'all',
      spurgeonStudyReference: null,
      handleOpenSpurgeonStudy: jest.fn(),
      handleCloseSpurgeonLibrary: jest.fn(),
      handleSpurgeonOpenScripture: jest.fn(),
      closeMorneveLibrary: jest.fn(),
      closeMcheynePlan: jest.fn(),
      dismissScriptureAndPractice: jest.fn(),
      closeBibleReader,
      memorizationPracticeVerse: null,
      closeMemorizationPractice: jest.fn(),
      updateMemorizationPracticeVerse: jest.fn(),
      handleOpenScriptureHighlight: jest.fn(),
      openMorneveLibrary: jest.fn(),
      openMcheynePlan: jest.fn(),
      handleOpenBibleReader: jest.fn(),
      handleMemorizationPracticeStart: jest.fn(),
      openStudyLibrary: jest.fn(),
    } as ProfileContentHooksSlice['studyModals'],
    navigateMcheynePlanDay: jest.fn(),
    navigateMcheyneLatest: jest.fn(),
    ...overrides,
  }
}
